### ISSUE TITLE
macOS, some mp4 tags missing

### ISSUE THREAD

**Issue by Kiatra** [jamerst/AutoTag#11]
Works great on macOS tagging mp4 files, but some tags are missing.

title: ok
programme: missing
season: missing
episode: missing
genre: ok

Not sure if this is a taglib issue. 

Might also be due to the media kind tag not being set. The tags for TV shows seem to not show without setting media kind in Apple TV. 

<img width="598" alt="Screenshot 2022-04-12 at 23 03 27" src="https://user-images.githubusercontent.com/9993201/163057389-8a497814-3af7-4b9d-b6cf-39a1bb28fce5.png">

<img width="399" alt="Screenshot 2022-04-12 at 23 31 06" src="https://user-images.githubusercontent.com/9993201/163057978-147a2990-488c-4367-8fb8-2d32c167b0b7.png">

The output on the command line and the renaming looks good though.
```
AutoTag v3.2.0
https://jtattersall.net

Star.Trek.Lower.Decks.S02E01.1080p.mkv:
    Found Star Trek Lower Decks S02E01 (Strange Energies) on TheMovieDB
    Successfully tagged file as Star Trek: Lower Decks S02E01 (Strange Energies)
    Successfully renamed file to 'Star Trek: Lower Decks - 2x01 - Strange Energies.mkv'


File successfully processed.
```

Not sure if you support mp4 tagging would be really nice though!

**Comment by jamerst** [comment]
The tags should be written to the file, it's possible that Apple TV is using different tag names to the standard though.

I also don't know how the media kind is stored, knowing Apple it might not be stored in the file itself.

Could you upload a small demo file that is tagged correctly according to Apple TV?

mp4 files are supported, though the extended tagging mode is only supported for mkv files.

**Comment by jamerst** [comment]
Thanks for providing the file.

I've had a look at it and I think I've managed to work out where Apple TV is storing/reading the data from.

I've attempted to write the tags with TagLib, however I'm not sure if they're correct. MediaInfo doesn't read them all correctly compared to the original file, though they should be identical in theory.

Please could you try opening this file in Apple TV to see if the tags are read correctly now? 

https://user-images.githubusercontent.com/10601770/164908969-75f81b0c-e2e5-4f27-9121-ac142028f307.mp4

**Comment by Kiatra** [comment]
Looks like some progress was made! The file was tagged mostly correctly except the episode number is empty, instead episodeid is set with the episode number.

Comparing the file you uploaded with one tagged via "Apple TV" with ffmpeg:

`ffmpeg -i testfile.mp4  -f ffmetadata`

I saw that the episode number should go into the "episode_sort"

**Comment by jamerst** [comment]
The episode_sort tag should now be set instead, would you mind checking how it displays in Apple TV again with this new file?

https://user-images.githubusercontent.com/10601770/164945310-d99bf3da-00f8-48ff-a7a4-fdb2b4f88f6f.mp4

For some reason ffmpeg is reporting the episode_sort value as 7 for that file, but I can't work out why. Checking the file with a hex editor confirms the value in the file appears to be 10, so I'm not sure what's going on there. I'm hoping Apple TV recognises it correctly as 10?

**Comment by Kiatra** [comment]
Succes! :)

<img width="320" alt="Screenshot 2022-04-23 at 23 08 47" src="https://user-images.githubusercontent.com/9993201/164946040-c283e7ad-6fcf-4ba7-82c2-5f6f5a10a738.png">

Interesting my ffmpeg also shows 7. But Apple TV correctly shows 10.

Thanks for the fix! I will then be able to sync shows to my iPad via Apple TV :)

**Comment by jamerst** [comment]
I've now uploaded v3.3.0 which will write the Apple tags to mp4 files when used with the argument `--apple-tagging`.

It also sets the media type for movies too, so any Apple products will also recognise them as movies.
