### ISSUE TITLE
[Question] tvRenamePattern doesn't reflect the rename

### ISSUE THREAD

**Issue by emagra** [jamerst/AutoTag#13]
Hi, I'm trying this software, seems good but I can't get the file name right.
I have change in "`~/.config/autotag/conf.json`"
`"tvRenamePattern": "%1 - S%2:00E%3:00 - %4",`

to have "Series - S01E01 - Title.mkv", format but when I rename some file i get this:
`AutoTag v3.3.1`
`https://jtattersall.net`
`Adding file '../../tvnamer/House.of.the.Dragon.S01E01.The.Heirs.of.the.Dragon.1080p.WEB-DL.DD5.1.H.264-MiU.mkv'`

`../../tvnamer/House.of.the.Dragon.S01E01.The.Heirs.of.the.Dragon.1080p.WEB-DL.DD5.1.H.264-MiU.mkv:`
`    Found House of the Dragon S01E01 (The Heirs of the Dragon) on TheMovieDB`
`    Successfully tagged file as House of the Dragon S01E01 (The Heirs of the Dragon)`
`    Successfully renamed file to 'House of the Dragon - 1x01 - The Heirs of the Dragon.mkv'`

`File successfully processed.`

What i need to change?

**Comment by jamerst** [comment]
Looks like this is a bug. I can't see the problem at a glance, but I'll look into it further as soon as I can.

As a temporary workaround you can use the `--tv-pattern` command-line argument, that works as expected.

**Comment by jamerst** [comment]
Fixed in v3.3.2.
