### ISSUE TITLE
[Question] is the scope of this project to rename .srt file too?

### ISSUE THREAD

**Issue by emagra** [jamerst/AutoTag#14]
As in title. Or is there an option I'm missing?

Ty

**Comment by jamerst** [comment]
That's not a feature currently, it's certainly possible to add though if it's a feature you would use?

**Comment by emagra** [comment]
Well yes, I would use it for sure, so if you can implement it, this would be great. 

I'm Italian so i have the video file and I have to download the subtitle. I had some script to rename the video and sub file with the death [TVNamer](https://github.com/dbr/tvnamer) and them merge it with mkvtools.

**Comment by jamerst** [comment]
Released in v3.4.0.

To enable subtitle renaming, use the `--rename-subs` argument.

This assumes that the name of the subtitle file is the same as the name of the video file, but it will still work if they are not the same (but will be potentially less efficient).
