### ISSUE TITLE
Suggestion: Language support

### ISSUE THREAD

**Issue by scholt** [jamerst/AutoTag#15]
Hello there, first I want to say thank you for this really awesome tool! I appreciate your effort and work you put into this!

One thing I want to suggest, and hope you consider would be worth adding, is language support. A default language in the config file that could be overridden with a parameter like the other parameters. The language setting then affects the language of the metadata which is written to the file, as well as the file naming for show and episode titles.

Cheers

**Comment by jamerst** [comment]
I have added this feature, but it's not ready for release yet unfortunately due to some problems with updating to .NET 7.

The work to fix that should be done and released in the next few days

**Comment by jamerst** [comment]
Released in v3.5.0.

Simply pass a [ISO 639-1 language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (e.g. `de`) as a value for the `-l` or `--language` parameter.

**Comment by scholt** [comment]
Awesome! Thank you very much!
