### ISSUE TITLE
Autoselect a Default Option

### ISSUE THREAD

**Issue by genius-is** [jamerst/AutoTag#17]
There are some instances where a video file will return multiple options. Is there an argument to select the first option by default?

**Comment by jamerst** [comment]
This has been resolved in v3.5.2.

The manual mode behaviour is now consistent between TV and movie mode. Previously the prompt to select a result would be shown for movies if the title of the first result didn't match the parsed title exactly. Now the behaviour is the same as TV mode (only show when manual mode is enabled).
