### ISSUE TITLE
File Name Character Substitution

### ISSUE THREAD

**Issue by MavenTek** [jamerst/AutoTag#18]
When renaming movie files, AutoTag removes invalid characters, such as the colon ":" . Instead of removing invalid characters, would it be possible to have an option that can be used for substituting characters? For example, if movie title includes a colon ":", substitute for a dash "-".

**Comment by jamerst** [comment]
This feature has been added in [v3.5.3](https://github.com/jamerst/AutoTag/releases/tag/v3.5.3).

It uses the `--replace` option, so for your use case you should pass `--replace : -`
