### ISSUE TITLE
mkv - file not writeable

### ISSUE THREAD

**Issue by zyw80** [jamerst/AutoTag#2]
When i'm trying to tag a mkv file encoded by handbrake i'm getting the message "error: could not tag file - file not writeable", even when there is no process locking it. If i remux the file with mkvtoolnix i can tag it without problems, so it must be something about how handbrake mux the streams?

**Comment by jamerst** [comment]
I believe this is an issue with the tagging library, taglib-sharp. It raises that exception when it detects the file as corrupted.

I've not managed to work out why it detects some files as corrupted when they're not. I will try to investigate this further at some point.

**Comment by jamerst** [comment]
I believe this is now fixed in v3.0.0 from my limited testing. Not entirely sure why, I presume taglib-sharp 2.2.0 fixes the issue.

Could you please confirm it is fixed by testing with any files you previously had problems with?

**Comment by zyw80** [comment]
Yes it's working!!
