### ISSUE TITLE
extended tagging on mkv - suggestions

### ISSUE THREAD

**Issue by jimlynnjulian** [jamerst/AutoTag#22]
autotag -t --extended-tagging "Smack the Pony - 1x02 - Episode 2.mkv"
The same with :  "Silicon Valley - 01x01 - Minimum Viable Product.mkv"
There's only technical data added if the '-t' option is used alone. Even with extended tagging, there cpould be more data.
I write this with media server applications like Jellyfiin and Plex in mind.
The metadata includes the series name in the filename only. There's no cast, The 'Movie name' (episode title) is repeated.
I suggest the series title be included elsewhere than the filename. Major cast menbers hould be added and maybe the director.
Explicit instruction/example on doing batch mode would help. This example was done single file.

**Comment by jamerst** [comment]
Sorry for the delay!

The issue with the extended tags (director, cast and cast roles) not being written has been resolved.

I have also resolved the issue with the title being set as the album in Matroska files. This is a bug with the tagging library (mono/taglib-sharp#263) that is over 2 years old and shows no sign of being fixed, despite being very simple to resolve. Thankfully it is pretty easy to work around.

Can't believe I never noticed that bug with the album tag!

Regarding batch mode, you don't need to do anything specific. Just provide a path to a directory or multiple paths as arguments when invoking from the command line. Directories are searched recursively for any files to tag.

Note that there is currently an issue with some arguments which mean they need to be put at the end of the argument list ([see readme](https://github.com/jamerst/AutoTag#-known-issue-)). One of the affected arguments is `--extended-tagging`, so you should make sure to run `autotag -t [paths] --extended-tagging` instead.
