### ISSUE TITLE
Tagging differs from Matroska conventions

### ISSUE THREAD

**Issue by livinggreener** [jamerst/AutoTag#9]
In TV mode I'm seeing some tags not quite matching up with the conventions laid out by Matroska (https://www.matroska.org/technical/tagging.html).
(1) The tag with TargetTypeValue of 60 should have TargetType equal to SEASON, but AutoTag sets it to VOLUME...technically acceptable but not accurately descriptive.
(2)AutoTag doesn't add any tag of TargetTypeValue 50. This should be present and with nested tag NAME of TITLE with VALUE/string equal to the episode's title. Instead AutoTag is placing the episode title within Segment information/Title.

**Comment by jamerst** [comment]
This issue should be reported to the maintainers of [taglib-sharp](https://github.com/mono/taglib-sharp/).
